
name: nyproject

on:
    push:
        branches:
           -main

jobs:
 build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      name: checkoutcode
      uses: actions/checkout@v2
      name: install dependencies
      run: npm run install
      name: Build project
      run: npm run build
      name: Test project
      run: npm run test
      name: Deploy project
      run: npm run deploy
      
    
